my_tuple=("Dan","raya","heza")
print("name tuple is: ",my_tuple)
name_list=list(my_tuple)
print("name list is: ",name_list)
print("type of my_list is : ",type(name_list))
name_list.append("rejosh")
my_tuple=tuple(name_list)
print("tuple is unchangable.but we add an element by converting it into list and back into tuple: ",my_tuple)
print("type of my_tuple is : ",type(my_tuple))